=== drmikecrowe/mbfcext/docs/v5/schema/biasModel.json
{
    "$id": "http://supermodel.io/drmikecrowe/mbfc/biasModel",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "bias-model",
    "description": "A bias record",
    "type": "object",
    "properties": {
        "bias": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/biasEnums"
        },
        "name": {
            "title": "Name",
            "description": "The human-friendly name of the bias",
            "type": "string",
            "examples": [
                "Center"
            ]
        },
        "description": {
            "type": "string",
            "examples": [
                "These media sources are moderately to strongly biased toward liberal causes through story selection and/or political affiliation.  They may utilize strong loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes), publish misleading reports and omit reporting of information that may damage liberal causes. Some sources in this category may be untrustworthy."
            ],
            "title": "Description",
            "description": "The description of the bias"
        },
        "url": {
            "type": "string",
            "examples": [
                "https://mediabiasfactcheck.com/center/"
            ],
            "title": "URL",
            "description": "The URL on https://mediabiasfactcheck.com for the bias"
        },
        "pretty": {
            "type": "string",
            "examples": [
                "Center"
            ],
            "title": "Pretty",
            "description": "The human friendly name for the bias"
        },
        "code": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/biasCodes"
        }
    },
    "required": [
        "bias",
        "name",
        "description",
        "url",
        "pretty",
        "code"
    ]
}

=== drmikecrowe/mbfcext/docs/v5/data/biases.json
[{"bias":"left","code":"L","description":"These media sources are moderately to strongly biased toward liberal causes through story selection and/or political affiliation.  They may utilize strong loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes), publish misleading reports and omit reporting of information that may damage liberal causes. Some sources in this category may be untrustworthy.","name":"Left Bias","pretty":"Left","url":"https://mediabiasfactcheck.com/left/"},{"bias":"left-center","code":"LC","description":"These media sources have a slight to moderate liberal bias.  They often publish factual information that utilizes loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes) to favor liberal causes.  These sources are generally trustworthy for information, but may require further investigation.  ","name":"Left-Center Bias","pretty":"Left-Center","url":"https://mediabiasfactcheck.com/leftcenter/"},{"bias":"center","code":"C","description":"These sources have minimal bias and use very few loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes).  The reporting is factual and usually sourced.  These are the most credible media sources.  ","name":"Least Biased","pretty":"Center","url":"https://mediabiasfactcheck.com/center/"},{"bias":"right-center","code":"RC","description":"These media sources are slightly to moderately conservative in bias. They often publish factual information that utilizes loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes) to favor conservative causes. These sources are generally trustworthy for information, but may require further investigation.  ","name":"Right-Center Bias","pretty":"Right-Center","url":"https://mediabiasfactcheck.com/right-center/"},{"bias":"right","code":"R","description":"These media sources are moderately to strongly biased toward conservative causes through story selection and/or political affiliation. They may utilize strong loaded words (wording that attempts to influence an audience by using appeal to emotion or stereotypes), publish misleading reports and omit reporting of information that may damage conservative causes. Some sources in this category may be untrustworthy.","name":"Right Bias","pretty":"Right","url":"https://mediabiasfactcheck.com/right/"},{"bias":"pro-science","code":"PS","description":"These sources consist of legitimate science or are evidence based through the use of credible scientific sourcing.  Legitimate science follows the scientific method, is unbiased and does not use emotional words.  These sources also respect the consensus of experts in the given scientific field and strive to publish peer reviewed science. Some sources in this category may have a slight political bias, but adhere to scientific principles.","name":"Pro-Science","pretty":"Pro-Science","url":"https://mediabiasfactcheck.com/pro-science/"},{"bias":"conspiracy-pseudoscience","code":"CP","description":"Sources in the Conspiracy-Pseudoscience category may publish unverifiable information that is not always supported by evidence. These sources may be untrustworthy for credible/verifiable information, therefore fact checking and further investigation is recommended on a per article basis when obtaining information from these sources. ","name":"Conspiracy-Pseudoscience","pretty":"Conspiracy-Pseudoscience","url":"https://mediabiasfactcheck.com/conspiracy/"},{"bias":"satire","code":"S","description":"These sources exclusively use humor, irony, exaggeration, or ridicule to expose and criticize people’s stupidity or vices, particularly in the context of contemporary politics and other topical issues. Primarily these sources are clear that they are satire and do not attempt to deceive.","name":"Satire","pretty":"Satire","url":"https://mediabiasfactcheck.com/satire/"},{"bias":"fake-news","code":"FN","description":"A questionable source exhibits one or more of the following: extreme bias, overt propaganda, poor or no sourcing to credible information and/or is fake news. Fake News is the deliberate attempt to publish hoaxes and/or disinformation for the purpose of profit or influence (Learn More). Sources listed in the Questionable Category may be very untrustworthy and should be fact checked on a per article basis. Please note sources on this list are not considered fake news unless specifically written in the notes section for that source.","name":"Questionable Sources","pretty":"Fake-News","url":"https://mediabiasfactcheck.com/fake-news/"}]
