=== drmikecrowe/mbfcext/docs/v5/schema/credibilityModel.json
{
    "$id": "http://supermodel.io/drmikecrowe/mbfc/credibilityModel",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "credibility-model",
    "description": "credibility-model model description",
    "type": "object",
    "properties": {
        "credibility": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/credibilityEnums"
        },
        "code": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/credibilityCodes"
        },
        "name": {
            "type": "string"
        },
        "pretty": {
            "type": "string"
        }
    },
    "required": [
        "credibility",
        "code",
        "name",
        "pretty"
    ]
}

=== drmikecrowe/mbfcext/docs/v5/data/credibility.json
[{"code":"H","credibility":"high-credibility","name":"High Credibility","pretty":"High Credibility"},{"code":"M","credibility":"medium-credibility","name":"Medium Credibility","pretty":"Medium Credibility"},{"code":"L","credibility":"low-credibility","name":"Low Credibility","pretty":"Low Credibility"},{"code":"NA","credibility":"n/a","name":"N/A","pretty":"N/A"}]
