=== drmikecrowe/mbfcext/docs/v5/schema/questionableModel.json
{
    "$id": "http://supermodel.io/drmikecrowe/mbfc/questionableModel",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "questionable-model",
    "description": "questionable-model model description",
    "type": "object",
    "properties": {
        "questionable": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/questionableEnums"
        },
        "code": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/questionableCodes"
        },
        "name": {
            "type": "string"
        },
        "pretty": {
            "type": "string"
        }
    },
    "required": [
        "questionable",
        "code",
        "name",
        "pretty"
    ]
}

=== drmikecrowe/mbfcext/docs/v5/data/questionable.json
[{"code":"NA","name":"N/A","pretty":"N/A","questionable":"n/a"},{"code":"C","name":"Conspiracy","pretty":"Conspiracy","questionable":"conspiracy"},{"code":"P","name":"Propaganda","pretty":"Propaganda","questionable":"propaganda"},{"code":"PS","name":"Poor Sourcing","pretty":"Poor Sourcing","questionable":"poor-sourcing"},{"code":"LOT","name":"Lack of Transparency","pretty":"Lack of Transparency","questionable":"lack-of-transparency"},{"code":"FFC","name":"Failed Fact Checks","pretty":"Failed Fact Checks","questionable":"failed-fact-checks"},{"code":"FC","name":"False Claims","pretty":"False Claims","questionable":"false-claims"},{"code":"M","name":"Misinformation","pretty":"Misinformation","questionable":"misinformation"},{"code":"H","name":"Hate","pretty":"Hate","questionable":"hate"},{"code":"P","name":"Plagiarism","pretty":"Plagiarism","questionable":"plagiarism"},{"code":"FN","name":"Fake News","pretty":"Fake News","questionable":"fake-news"},{"code":"P","name":"Pseudoscience","pretty":"Pseudoscience","questionable":"pseudoscience"},{"code":"IM","name":"Imposter","pretty":"Imposter","questionable":"imposter"},{"code":"C","name":"Censorship","pretty":"Censorship","questionable":"censorship"}]
