=== drmikecrowe/mbfcext/docs/v5/schema/reportingModel.json
{
    "$id": "http://supermodel.io/drmikecrowe/mbfc/reportingModel",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "reporting-model",
    "description": "reporting-model model description",
    "type": "object",
    "properties": {
        "reporting": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/reportingEnums"
        },
        "code": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/reportingCodes"
        },
        "name": {
            "type": "string"
        },
        "pretty": {
            "type": "string"
        }
    },
    "required": [
        "reporting",
        "code",
        "name",
        "pretty"
    ]
}

=== drmikecrowe/mbfcext/docs/v5/data/reporting.json
[{"code":"VH","name":"Very-High","pretty":"Very-High","reporting":"very-high"},{"code":"H","name":"High","pretty":"High","reporting":"high"},{"code":"MF","name":"Mostly-Factual","pretty":"Mostly-Factual","reporting":"mostly-factual"},{"code":"M","name":"Mixed","pretty":"Mixed","reporting":"mixed"},{"code":"L","name":"Low","pretty":"Low","reporting":"low"},{"code":"VL","name":"Very-Low","pretty":"Very-Low","reporting":"very-low"}]
