=== drmikecrowe/mbfcext/docs/v5/schema/trafficModel.json
{
    "$id": "http://supermodel.io/drmikecrowe/mbfc/trafficModel",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "traffic-model",
    "description": "traffic-model model description",
    "type": "object",
    "properties": {
        "traffic": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/trafficEnums"
        },
        "code": {
            "$ref": "http://supermodel.io/drmikecrowe/mbfc/trafficCodes"
        },
        "name": {
            "type": "string"
        },
        "pretty": {
            "type": "string"
        }
    },
    "required": [
        "traffic",
        "code",
        "name",
        "pretty"
    ]
}

=== drmikecrowe/mbfcext/docs/v5/data/traffic.json
[{"code":"N","name":"No Data","pretty":"No Data","traffic":"no-data"},{"code":"M","name":"Minimal Traffic","pretty":"Minimal Traffic","traffic":"minimal-traffic"},{"code":"M","name":"Medium Traffic","pretty":"Medium Traffic","traffic":"medium-traffic"},{"code":"H","name":"High Traffic","pretty":"High Traffic","traffic":"high-traffic"}]
